remoteproc: k3-m4: add missing security.h include
This change fixes following build error:

drivers/remoteproc/ti_k3_m4_rproc.c:151:9: error:
implicit declaration of function 'ti_secure_image_post_process'

Upstream-Status: Inappropriate [other]

This is downstream specific so far. This file is not present in mainline.

Related-to: ELB-5351

Signed-off-by: Andrejs Cainikovs <andrejs.cainikovs@toradex.com>