board: toradex: verdin-am62: avoid relocated u-boot and reserved-memory overlap
On 512 MB SoM uboot is relocated at addresses flagged as reserved-memory in
the device tree (see k3-am62-verdin.dtsi).
These memory areas are really used by other cores and software components,
so the clash must be avoided.
The net effect range between hung uboot or uboot lmb complaining it cannot
reserve some memory areas while loading dt:

ERROR: reserving fdt memory region failed (addr=9e780000 size=80000 flags=4)
ERROR: reserving fdt memory region failed (addr=9e800000 size=1800000 flags=4)
ERROR: reserving fdt memory region failed (addr=9db00000 size=c00000 flags=4)

Set ram_top so relocated uboot no more clash with these reserved-memory areas.

Upstream-Status: Pending

This patch will be integrated into the Verdin AM62 initial support series.
https://lore.kernel.org/all/20230715074050.941051-1-marcel@ziswiler.com/

Signed-off-by: Emanuele Ghidoli <emanuele.ghidoli@toradex.com>