board: ti: am62p: Fix compilation warning for implicit declaration
Fixes below warning by including cpu_funcs.h:

"board/ti/am62px/evm.c: In function `spl_board_init`:
board/ti/am62px/evm.c:83:9: warning: implicit declaration of function
`enable_caches` [-Wimplicit-function-declaration]
   83 |         enable_caches();"
      |         ^~~~~~~~~~~~~

While at it, also sort the include headers by placing video.h at the
end.

Fixes: a7e8f56abf9 ("board: ti: am62p: Add splash screen support")
Reviewed-by: Kamlesh Gurudasani <kamlesh@ti.com>
Signed-off-by: Devarsh Thakkar <devarsht@ti.com>