misc: uclass: Fix compile error
Add #include <dm/ofnode.h> to fix the following compiler error

+In file included from drivers/pinctrl/nxp/pinctrl-scu.c:11:
+include/misc.h:87:25: error: unknown type name 'ofnode'
+   87 | int misc_init_by_ofnode(ofnode node);
+      |                         ^~~~~~

Upstream-Status: Inappropriate [other]

The fixed commit is present only on the downstream TI branch,
therefore there is nothing to send to upstream denx repository.
We might think about sending this patch to TI in the future.

Fixes: 9d9fd0a3b18f ("misc: uclass: Introduce misc_init_by_ofnode")
Signed-off-by: Francesco Dolcini <francesco.dolcini@toradex.com>